version: '3.8'

services:
  db:
    image: mysql:8
    container_name: coffee_app_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coffee_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: coffee_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  db_data:
